const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"赛事类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionarySaishi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"时间段管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShijianduan"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"赛事信息管理",
                        "menuJump":"列表",
                        "tableName":"saishi"
                    }
                ],
                "menu":"赛事信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核",
                            "删除"
                        ],
                        "menu":"赛事报名管理",
                        "menuJump":"列表",
                        "tableName":"saishibaoming"
                    }
                ],
                "menu":"赛事报名管理"
            }
			
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"赛事成绩管理",
                        "menuJump":"列表",
                        "tableName":"saishifenshu"
                    }
                ],
                "menu":"赛事成绩管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "报表",
			                "删除"
			            ],
			            "menu":"赛队成绩管理",
			            "menuJump":"列表",
			            "tableName":"saiduichengji"
			        }
			    ],
			    "menu":"赛队成绩管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"日程信息管理",
			            "menuJump":"列表",
			            "tableName":"richeng"
			        }
			    ],
			    "menu":"日程信息管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "导入导出",
                            "删除"
                        ],
                        "menu":"运动员管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"运动员管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "报名",
	                    ],
	                    "menu":"赛事信息管理",
	                    "menuJump":"列表",
	                    "tableName":"saishi"
	                }
	            ],
	            "menu":"赛事信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"赛事报名管理",
	                    "menuJump":"列表",
	                    "tableName":"saishibaoming"
	                }
	            ],
	            "menu":"赛事报名管理"
	        }
			
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"赛事成绩管理",
	                    "menuJump":"列表",
	                    "tableName":"saishifenshu"
	                }
	            ],
	            "menu":"赛事成绩管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"赛队成绩管理",
			            "menuJump":"列表",
			            "tableName":"saiduichengji"
			        }
			    ],
			    "menu":"赛队成绩管理"
			}
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"运动员",
	    "tableName":"yonghu"
	}
]
    }
}
export default menu;
